### ISSUE TITLE
大佬 求救

### ISSUE THREAD

**Issue by Rich-wz** [deximy/FxxkCiDaRen#7]
能否加一下您的q或者您加一下我 27477109 弄好请大佬喝奶茶 区域网配置不成，

**Comment by deximy** [comment]
这个项目目前已经不再维护了，不保证连接后可以正常使用。

**Comment by Rich-wz** [comment]
没事的 想试试 太难了英语 实在整不了这玩意。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 晚上6:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deximy/FxxkCiDaRen] 大佬 求救 (#7)





 
这个项目目前已经不再维护了，不保证连接后可以正常使用。

**Comment by deximy** [comment]
已修复
